#!/bin/bash -e

COMMIT=`git rev-parse HEAD`
TAG=$(git describe --exact-match --abbrev=0 --tags ${COMMIT} 2> /dev/null || true)

if [ -z "$TAG" ]; then
	VERSION=$COMMIT
else
	VERSION=$TAG
fi

# check for changed files (not untracked files)
if [ -n "$(git diff --shortstat 2> /dev/null | tail -n1)" ]; then
    VERSION="${VERSION}+dirty"
fi

export GOPATH="$(pwd)/_output"
export KUBEAWS="$GOPATH/src/github.com/coreos/coreos-kubernetes/multi-node/aws"

if [ -d $GOAPTH ]; then
    rm -rf $GOPATH
fi

mkdir -p $GOPATH/src
cp -r ./vendor/* $GOPATH/src
mkdir -p $KUBEAWS
cp -r ./pkg $KUBEAWS/pkg
cp -r ./cmd $KUBEAWS/cmd

go build -ldflags "-X main.VERSION=${VERSION}" -a -tags netgo -installsuffix netgo -o bin/kube-aws github.com/coreos/coreos-kubernetes/multi-node/aws/cmd/kube-aws
