#!/bin/bash -e

# define location of openssl binary manually since running this
# script under Vagrant fails on some systems without it
OPENSSL=/usr/bin/openssl

function usage {
    echo "USAGE: $0 <output-dir> [CONTROLLER_SAN,CONTROLLER_SAN] [WORKER_SAN,WORKER_SAN]"
    echo "  example: $0 ./ssl IP.1=127.0.0.1,IP.2=10.0.0.1 IP.1=172.16.8.4,IP.2=172.16.8.6"
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

if [ ! -d $1 ]; then
    echo "ERROR: output directory does not exist: $1"
    exit 1
fi

OUTDIR=$1
API_SANS=$2
WORKER_SANS=$3

OUTFILE_CONTROLLER="$OUTDIR/controller.tar"
OUTFILE_WORKER="$OUTDIR/worker.tar"

CNF_TEMPLATE="
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name

[req_distinguished_name]

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
"
echo "Generating SSL artifacts in $OUTDIR"

# Add SANs to openssl config
echo "$CNF_TEMPLATE$(echo $API_SANS | tr ',' '\n')" > $OUTDIR/apiserver-req.cnf
echo "$CNF_TEMPLATE$(echo $WORKER_SANS | tr ',' '\n')" > $OUTDIR/worker-req.cnf

# establish cluster CA and self-sign a cert
$OPENSSL genrsa -out $OUTDIR/ca-key.pem 2048
$OPENSSL req -x509 -new -nodes -key $OUTDIR/ca-key.pem -days 10000 -out $OUTDIR/ca.pem -subj "/CN=kube-ca"

# create apiserver key and signed cert
$OPENSSL genrsa -out $OUTDIR/apiserver-key.pem 2048
$OPENSSL req -new -key $OUTDIR/apiserver-key.pem -out $OUTDIR/apiserver.csr -subj "/CN=kube-apiserver" -config $OUTDIR/apiserver-req.cnf
$OPENSSL x509 -req -in $OUTDIR/apiserver.csr -CA $OUTDIR/ca.pem -CAkey $OUTDIR/ca-key.pem -CAcreateserial -out $OUTDIR/apiserver.pem -days 365 -extensions v3_req -extfile $OUTDIR/apiserver-req.cnf

# create worker key and signed cert
$OPENSSL genrsa -out $OUTDIR/worker-key.pem 2048
$OPENSSL req -new -key $OUTDIR/worker-key.pem -out $OUTDIR/worker.csr -subj "/CN=kube-worker" -config $OUTDIR/worker-req.cnf
$OPENSSL x509 -req -in $OUTDIR/worker.csr -CA $OUTDIR/ca.pem -CAkey $OUTDIR/ca-key.pem -CAcreateserial -out $OUTDIR/worker.pem -days 365 -extensions v3_req -extfile $OUTDIR/worker-req.cnf

# create admin key and signed cert
$OPENSSL genrsa -out $OUTDIR/admin-key.pem 2048
$OPENSSL req -new -key $OUTDIR/admin-key.pem -out $OUTDIR/admin.csr -subj "/CN=kube-admin"
$OPENSSL x509 -req -in $OUTDIR/admin.csr -CA $OUTDIR/ca.pem -CAkey $OUTDIR/ca-key.pem -CAcreateserial -out $OUTDIR/admin.pem -days 365

tar -cf $OUTFILE_CONTROLLER -C $OUTDIR/ ca.pem apiserver.pem apiserver-key.pem
tar -cf $OUTFILE_WORKER -C $OUTDIR/ ca.pem worker.pem worker-key.pem

echo "Bundled controller SSL artifacts into $OUTFILE_CONTROLLER"
echo "Bundled worker SSL artifacts into $OUTFILE_WORKER"
